apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::539812135697:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-L4O227YGJUHK
      username: system:node:{{EC2PrivateDNSName}}
    - groups:  
      - system:masters
      rolearn: arn:aws:iam::539812135697:role/UdacityFlaskDeployCBKubectlRole
      username: build 
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-01T11:56:10Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1604"
  uid: bd73bbc5-0370-406d-b2c8-4064379245cd
